# Copyright (c) 2026 Arne Wendt (@bitmeal)
# SPDX-License-Identifier: MPL-2.0

## MCUBoot bootloader config
SB_CONFIG_BOOTLOADER_MCUBOOT=y
SB_CONFIG_MCUBOOT_MODE_SWAP_USING_MOVE=y
SB_CONFIG_BOOT_SIGNATURE_TYPE_RSA=y
SB_CONFIG_BOOT_SIGNATURE_KEY_FILE="\${APP_DIR}/mcuboot.pem"

## build system configuration
# use partitions from device tree fstab.dtsi
SB_CONFIG_PARTITION_MANAGER=n

SB_CONFIG_WARN_EXPERIMENTAL=n

## output artifacts
SB_CONFIG_DFU_ZIP=y
# # generate merged.hex; currently broken in v3.2.4 with sysbuild; workaround in ./sysbuild/CMakeLists.txt
# SB_CONFIG_MERGED_HEX_FILES=y
