name: Builder

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

env:
  NRF_TOOLCHAIN_VERSION: v2.7.0
  NRF_SDK_VERSION: v2.7.0
  APP_REPO_ROOT: /app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies + West + NRF Util
        run: |
          sudo apt update
          sudo apt install --no-install-recommends \
            curl \
            git \
            python3 python3-pip \

          pip3 install --break-system-packages west

          curl https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o /usr/bin/nrfutil
          chmod +x /usr/bin/nrfutil
          nrfutil install toolchain-manager

      - name: Restore NCS
        id: cache-ncs-restore
        uses: actions/cache/restore@v4
        with:
          path: ~/ncs/
          key: ncs-${{ runner.os }}-${NRF_TOOLCHAIN_VERSION}-${NRF_SDK_VERSION}

      - uses: actions/checkout@v4
        with:
          path: ${APP_REPO_ROOT}

      - name: Fetch Toolchain + NRF & ANT SDK
        if: steps.cache-ncs-restore.outputs.cache-hit != 'true'
        run: |
          # install toolchain
          nrfutil toolchain-manager install --ncs-version ${NRF_TOOLCHAIN_VERSION}

          # install nrf sdk
          mkdir -p ~/ncs/sdks/
          cd ~/ncs/sdks/
          west init -m https://github.com/nrfconnect/sdk-nrf --mr ${NRF_SDK_VERSION} ${NRF_SDK_VERSION}
          cd ~/ncs/sdks/${NRF_SDK_VERSION}/
          west update

          # install ant sdk
          west config manifest.group-filter +ant
          west update
          pushd ~/ncs/sdks/${NRF_SDK_VERSION}/ant && git apply --whitespace=fix ${APP_REPO_ROOT}/ant_sdk_nrf52832.patch && popd
          west list ant

          # finalize sdk install
          nrfutil toolchain-manager launch -- west zephyr-export

      - name: Save NCS
        if: steps.cache-ncs-restore.outputs.cache-hit != 'true'
        id: cache-ncs-save
        uses: actions/cache/save@v4
        with:
          path: ~/ncs/
          key: ncs-${{ runner.os }}-${NRF_TOOLCHAIN_VERSION}-${NRF_SDK_VERSION}

      - name: Build Application
        id: app-build
        working-directory: ~/ncs/sdks/${NRF_SDK_VERSION}/
        env:
          MCUBOOT_SIGNING_KEY: ${{ secrets.MCUBOOT_SIGNING_KEY }}
        run: |
          echo ${MCUBOOT_SIGNING_KEY} > ${APP_REPO_ROOT}/mcuboot.pem
          nrfutil toolchain-manager launch -- west build --board sks_airspy --build-dir ${APP_REPO_ROOT}/build/ --no-sysbuild ${APP_REPO_ROOT}

      - name: Save Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sks-airspy-community-firmware
          path: |
            ${APP_REPO_ROOT}/build/zephyr/merged.hex
            ${APP_REPO_ROOT}/build/zephyr/dfu_application.zip
