name: Builder

on:
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request_target:
    # prevent secret leaks by enabling: "Require approval for all external contributors" in repository settings "Actions">"General"
    types:
      - opened
      - synchronize
    branches:
      - master
  workflow_dispatch:

env:
  # NRF_TOOLCHAIN_VERSION: v2.7.0
  # NRF_SDK_VERSION: v2.7.0
  ANT_SDK_VERSION: v2.1.0
  SDK_LOCATION: /opt/sdk/

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare Environment & Dependencies
        run: |
          sudo apt update
          sudo apt install -y --no-install-recommends \
            curl \
            git \
            python3 python3-pip

          pip3 install --break-system-packages west

          curl https://files.nordicsemi.com/artifactory/swtools/external/nrfutil/executables/x86_64-unknown-linux-gnu/nrfutil -o /usr/local/bin/nrfutil
          chmod +x /usr/local/bin/nrfutil
          nrfutil install toolchain-manager

          nrfutil toolchain-manager config --set install-dir=${SDK_LOCATION}

          curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

          mkdir -p ${SDK_LOCATION}

      - name: Restore cached SDK
        id: cachesdk
        uses: actions/cache/restore@v5
        with:
          path: ${{ env.SDK_LOCATION }}
          key: sdk-${{ runner.os }}-${{ env.ANT_SDK_VERSION }}

      - name: Setup SDK
        if: steps.cachesdk.outputs.cache-hit != 'true'
        working-directory: ${{ env.SDK_LOCATION }}
        run: |
          # allow access
          git config --global credential.helper cache
          git ls-remote https://SKS_AIRSPY_ANT_TOKEN:${{ secrets.SKS_AIRSPY_ANT_TOKEN }}@github.com/ant-nrfconnect/sdk-ant > /dev/null
          # fetch SDK
          west init -m "https://github.com/ant-nrfconnect/sdk-ant" --mr ${ANT_SDK_VERSION} sdk-ant
          pushd sdk-ant && west update && popd

      - name: Setup Toolchain
        if: steps.cachesdk.outputs.cache-hit != 'true'
        working-directory: ${{ env.SDK_LOCATION }}/sdk-ant/
        run: |
          nrfutil toolchain-manager install --ncs-version $(yq '.manifest.projects.[] | select(.name == "nrf") | .revision' ${SDK_LOCATION}/sdk-ant/ant/west.yml)
          
          # finalize sdk install
          nrfutil toolchain-manager launch -- west zephyr-export

      - name: Finalize Setup
        working-directory: ${{ env.SDK_LOCATION }}/sdk-ant/
        run: |
          nrfutil toolchain-manager launch -- west zephyr-export

      - name: Checkout
        uses: actions/checkout@v6

      - name: Cache SDK
        if: steps.cachesdk.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ${{ env.SDK_LOCATION }}
          # key: sdk-${{ runner.os }}-${{ env.ANT_SDK_VERSION }}
          key: ${{ steps.cachesdk.outputs.cache-primary-key }}

      - name: Build Application
        id: app-build
        working-directory: ${{ env.SDK_LOCATION }}/sdk-ant/
        run: |
          echo "${{ secrets.MCUBOOT_SIGNING_KEY }}" > ${{ github.workspace }}/mcuboot.pem
          nrfutil toolchain-manager launch -- west build --board sks_airspy --build-dir ${{ github.workspace }}/build/ --sysbuild ${{ github.workspace }}
          echo "IMAGE_NAME=$(yq '.cmake.images.[] | select(.type == "MAIN") | .name' ${{ github.workspace }}/build/build_info.yml)" >> $GITHUB_OUTPUT

      - name: Compile Artifacts
        id: artifacts-compile
        working-directory: ${{ env.SDK_LOCATION }}/sdk-ant/
        # working-directory: ${{ github.workspace }}
        env:
          IMAGE_NAME: ${{ steps.app-build.outputs.IMAGE_NAME }}
        run: |
          nrfutil toolchain-manager launch -- west build --build-dir ${{ github.workspace }}/build/${IMAGE_NAME}/ --sysbuild -t ram_report
          nrfutil toolchain-manager launch -- west build --build-dir ${{ github.workspace }}/build/${IMAGE_NAME}/ --sysbuild -t rom_report

          cp ${{ github.workspace }}/build/${IMAGE_NAME}/ram.json ${{ github.workspace }}/build/app_ram.json
          cp ${{ github.workspace }}/build/${IMAGE_NAME}/rom.json ${{ github.workspace }}/build/app_rom.json

          cp ${{ github.workspace }}/build/${IMAGE_NAME}/zephyr/zephyr.elf ${{ github.workspace }}/build/app.elf
          cp ${{ github.workspace }}/build/${IMAGE_NAME}/zephyr/zephyr.hex ${{ github.workspace }}/build/app.hex
          cp ${{ github.workspace }}/build/${IMAGE_NAME}/zephyr/zephyr.signed.hex ${{ github.workspace }}/build/app.signed.hex
          cp ${{ github.workspace }}/build/mcuboot/zephyr/zephyr.elf ${{ github.workspace }}/build/mcuboot.elf
          cp ${{ github.workspace }}/build/mcuboot/zephyr/zephyr.hex ${{ github.workspace }}/build/mcuboot.hex

          set -o allexport
          source <(cat ${{ github.workspace }}/VERSION | tr -d ' ')
          set +o allexport

          touch ${{ github.workspace }}/build/report.yaml
          NCS_VERSION=$(yq '.manifest.projects.[] | select(.name == "nrf") | .revision' ${SDK_LOCATION}/sdk-ant/ant/west.yml) yq -i '.ncs_version = strenv(NCS_VERSION)' ${{ github.workspace }}/build/report.yaml
          yq -i '.ncs_version = strenv(ANT_SDK_VERSION)' ${{ github.workspace }}/build/report.yaml
          yq -i '.app_version = strenv(VERSION_MAJOR)+"."+strenv(VERSION_MINOR)+"."+strenv(PATCHLEVEL)' ${{ github.workspace }}/build/report.yaml

      - name: Save Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: sks-airspy-community-firmware
          path: |
            ${{ github.workspace }}/build/merged.hex
            ${{ github.workspace }}/build/dfu_application.zip
            ${{ github.workspace }}/build/app_ram.json
            ${{ github.workspace }}/build/app_rom.json
            ${{ github.workspace }}/build/app.elf
            ${{ github.workspace }}/build/app.hex
            ${{ github.workspace }}/build/app.signed.hex
            ${{ github.workspace }}/build/mcuboot.elf
            ${{ github.workspace }}/build/mcuboot.hex
            ${{ github.workspace }}/build/report.yaml


  release:
    runs-on: ubuntu-24.04
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    env:
      VERSION_TAG_NAME: ${{ github.ref_name }}
      FILENAME_PREFIX: sascf
    needs: build
    steps:
      - uses: actions/checkout@v6

      # # TODO: prebuild version info artifact
      # - name: Cache SDK
      #   id: cachesdk
      #   uses: actions/cache/restore@v4
      #   with:
      #     path: /opt/sdk/
      #     key: sdk-${{ runner.os }}-${{ env.ANT_SDK_VERSION }}
      
      - uses: actions/download-artifact@v8
        with:
          name: sks-airspy-community-firmware
          path: release_artifacts
      
      - name: Prepare Release Notes
        run: |
          touch release_artifacts/NOTES

          echo "|Release | ${VERSION_TAG_NAME}|" >> release_artifacts/NOTES
          echo "|---|---|" >> release_artifacts/NOTES

          # read and write VERSION file version info
          set -o allexport
          source <(cat VERSION | tr -d ' ')
          set +o allexport
          echo "| APP | ${VERSION_MAJOR}.${VERSION_MINOR}.${PATCHLEVEL} |" >> release_artifacts/NOTES

          # # get ANT SDK version
          # ANT_SDK_VERSION=$(sed -n -E 's/.*ANT_VERSION_STRING\s+\"([[:digit:]\.]*)\".*$/\1/p;' /home/runner/ncs/sdks/${NRF_SDK_VERSION}/ant/include/ant_parameters.h)
          
          # # write SDKs and toolchain versions
          # echo "| nRF SDK | ${NRF_SDK_VERSION} |" >> release_artifacts/NOTES
          # echo "| ANT SDK | ${ANT_SDK_VERSION} |" >> release_artifacts/NOTES
          # echo "| Toolchain | ${NRF_TOOLCHAIN_VERSION} |" >> release_artifacts/NOTES          

      - name: Prepare Release Files
        run: |
          mv release_artifacts/merged.hex release_artifacts/${FILENAME_PREFIX}-${VERSION_TAG_NAME}-$(git describe --abbrev=7 --always).hex
          mv release_artifacts/dfu_application.zip release_artifacts/${FILENAME_PREFIX}_ota_dfu-${VERSION_TAG_NAME}-$(git describe --abbrev=7 --always).zip

      - name: Release
        env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create \
            ${VERSION_TAG_NAME} \
            release_artifacts/${FILENAME_PREFIX}*.hex \
            release_artifacts/${FILENAME_PREFIX}_ota_dfu*.zip \
            --title ${VERSION_TAG_NAME} \
            --notes-file release_artifacts/NOTES \
            --verify-tag \
            --latest \
            --target ${{ github.sha }} \
            --repo ${{ github.repository }}
          
